### ISSUE TITLE
navigation li

### ISSUE THREAD

**Issue by mikebutts** [crazymoo/ColmarAcademy#1]
https://github.com/crazymoo/ColmarAcademy/blob/deb0e5f794fdac4614e0dd1589a7b41a685180bf/index.html#L26-L31

![image](https://user-images.githubusercontent.com/8017734/33803025-2d7cbb34-dd54-11e7-9f5d-3ebd209facba.png)

take a look at the margins on this.

**Comment by crazymoo** [comment]
The specs didn't specify any type of margin except for the Sign in nav having a right margin of 24px.  I agree that it looks a bit crowded, so per your suggestion, I've added a small bit of left/right margin to the nav li elements.
