### ISSUE TITLE
right side width

### ISSUE THREAD

**Issue by mikebutts** [crazymoo/ColmarAcademy#2]
https://github.com/crazymoo/ColmarAcademy/blob/deb0e5f794fdac4614e0dd1589a7b41a685180bf/index.html#L58-L64

looks like the right side is justifying to the left, take a look at this and try to center i t

**Comment by crazymoo** [comment]
Again, the spec makes it look as though the banner column 2 should be left-justified.  But per your recommendation, I've adjusted it to center it within column 2.
