### ISSUE TITLE
flex divs

### ISSUE THREAD

**Issue by mikebutts** [crazymoo/ColmarAcademy#4]
https://github.com/crazymoo/ColmarAcademy/blob/deb0e5f794fdac4614e0dd1589a7b41a685180bf/index.html#L130-L214

You need to have an flex div, with 6 items inside, you can set the flex-basis or width to 30% and you will receive the desired effect.

**Comment by crazymoo** [comment]
I got rid of the column divs and am just using the courses-container div as a flex div with six anchor elements inside of it with a width of 30%.
